apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "task-manager.serviceAccountName" . }}
  labels:
    app.kubernetes.io/part-of: task-manager
{{- if eq .Values.secrets.provider "keyvault" }}
  annotations:
    {{- if not .Values.serviceAccount.workloadIdentityClientId }}
    {{- fail "serviceAccount.workloadIdentityClientId is required when secrets.provider=keyvault" }}
    {{- end }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentityClientId | quote }}
{{- end }}
